name: dakar301
description: "DAKAR 301 - Capture and share your videos"
publish_to: 'none'
version: 2.7.0+8

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
