name: dakar301
description: "Dania Media - Capture and share your videos"
publish_to: 'none'
version: 4.0.2+29

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  url_launcher: ^6.2.5
  workmanager: ^0.5.2
  connectivity_plus: ^6.0.3
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
