name: dakar301
description: "DAKAR 301 - Capture and share your videos"
publish_to: 'none'
version: 3.5.0+17

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.0
  share_plus: ^10.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
