name: dakar301
description: "DAKAR 301 - Capture and share your videos"
publish_to: 'none'
version: 3.6.0+18

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.2.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
